import type { Metadata } from "next";
import { Inter,Jost } from "next/font/google";
import "./globals.css";
import Header from "./header";
import AuthProvider from "@/components/AuthSession/nextauth-session-provider";

const inter = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shinka Jinzai | SIH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
